# Generated by Django 3.2.8 on 2022-10-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='userconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AddIndex(
            model_name='userconversation',
            index=models.Index(fields=['user', 'conversation'], name='chat_userco_user_id_2183fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userconversation',
            index=models.Index(fields=['conversation', 'user'], name='chat_userco_convers_6802d0_idx'),
        ),
    ]
