version: '3.7'

services:
  web:
    build: .
    command: python jbl_chat/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  test:
    build: .
    command: python jbl_chat/manage.py test chat
    volumes:
      - .:/code
